# Generated by Django 4.2.17 on 2024-12-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='code',
        ),
        migrations.AddField(
            model_name='item',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispatch.box'),
        ),
    ]
