# Generated by Django 4.2.17 on 2024-12-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_remove_item_code_item_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
        ),
    ]
