# Generated by Django 4.2.17 on 2024-12-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_item_code'),
    ]

    operations = [
    ]
